### ISSUE TITLE
Panic on map of slices

### ISSUE THREAD

**Issue by vfaronov** [cristalhq/aconfig#100]
Given the following code:
```
var cfg struct {
	Params url.Values
}
os.Setenv("PARAMS", "foo:bar")
err := aconfig.LoaderFor(&cfg, aconfig.Config{}).Load()
```
I would expect:
* either `cfg.Params = url.Values{"foo": {"bar"}}`
* or `err != nil`

Instead, the program panics with the following traceback:
<details><summary>panic: runtime error: invalid memory address or nil pointer dereference</summary>

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4e0fe7]

goroutine 1 [running]:
github.com/cristalhq/aconfig.(*Loader).setFieldData(0xc0000a2f70, 0xc0000ca160, 0x4f38c0, 0xc00009e710, 0x0, 0x0)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/reflection.go:178 +0x847
github.com/cristalhq/aconfig.(*Loader).setMap(0xc0000a2f70, 0xc0000ca000, 0xc0000b60b0, 0x7, 0x7, 0xc0000b607a)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/reflection.go:304 +0x439
github.com/cristalhq/aconfig.(*Loader).setFieldData(0xc0000a2f70, 0xc0000ca000, 0x4f38c0, 0xc00009e6b0, 0xc0000cc098, 0x539b01)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/reflection.go:199 +0xbfe
github.com/cristalhq/aconfig.(*Loader).setField(0xc0000a2f70, 0xc0000ca000, 0xc0000b607a, 0x6, 0xc0000a0240, 0xc00009ace0, 0xc0000b607a, 0x6)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/aconfig.go:433 +0x97
github.com/cristalhq/aconfig.(*Loader).loadEnvironment(0xc0000a2f70, 0x0, 0x0)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/aconfig.go:364 +0x165
github.com/cristalhq/aconfig.(*Loader).loadSources(0xc0000a2f70, 0xc00009e1f0, 0x0)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/aconfig.go:230 +0xf0
github.com/cristalhq/aconfig.(*Loader).loadConfig(0xc0000a2f70, 0x0, 0xc0000ba020)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/aconfig.go:201 +0x4e
github.com/cristalhq/aconfig.(*Loader).Load(0xc0000a2f70, 0xc0000ba018, 0x0)
	/home/vasiliy/.cache/gopath/pkg/mod/github.com/cristalhq/aconfig@v0.16.2/aconfig.go:191 +0x2f
main.main()
	/home/vasiliy/tmp/toy/toy.go:16 +0xc9
exit status 2
```

</details>

If the panic is intended behavior, it should be documented.

**Comment by cristaloleg** [comment]
Thanks for the issue, indeed it should not panic. Looks like there is a problem with type and it's handling. Will take a look.
